Fix: closing bracket missing in cli.py
```
File "/usr/local/lib/python3.5/dist-packages/cometblue/cli.py", line 130
    self._print_simple('Timeout in progress:\t%02u' % (value['current']))
       ^
SyntaxError: invalid syntax
```